import MainNav from "@/components/layouts/main-nav";
import { Toaster } from "@/components/ui/sonner";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Recipe Management System",
    template: "%s - Recipe Management System",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="pt-16">
          <MainNav />
          <main>{children}</main>
        </div>
        <Toaster position="top-right" richColors/>
      </body>
    </html>
  );
}
